### ISSUE TITLE
browser is offline?

### ISSUE THREAD

**Issue by hb8t** [emptygamer/pincat-browser#1]
Somehow I cant visit any site on my laptop, be it from Linux or windows version of the browser. Is it just me ?

**Comment by emptygamer** [comment]
Hello, 
it's not offline, did you click the "setURL" button?
or show something like "failed to load" in the title section?

Please provide system version, screenshots, and other information to assist with troubleshooting. :)

【Demo】https://www.youtube.com/watch?v=gYLQjXMGYXQ

**Comment by emptygamer** [comment]
If the issue is still not resolved, please reopen this issue :)
